trigger:
- master

pool:
    vmImage: 'windows-latest'

variables:
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@1
  displayName: 'Use .Net Core sdk '
  inputs:
    useGlobalJson: true

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    configuration: '$(buildConfiguration)'
    buildProperties: '$(buildPlatform)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/*[Tt]est/**/*.csproj'
    configuration: '$(buildConfiguration)'
    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)\TestResults\Coverage\ /p:Exclude="[xunit*]*"'

