version: '3.4'

services:
  blackcountrybot.web:
    image: ${REGISTRY:-blackcountrybot}/blackcountrybot.web:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sql.data

  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest