apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.svc.bot}}
  labels:
    app: {{template "bot-api.name" .}}
    chart: {{template "bot-api.chart" .}}
    release: {{.Release.Name}}
    heritage: {{.Release.Service}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{template "bot-api.name" .}}
    release: {{.Release.Name}}
