version: "3.4"

services:
  seq:
    image: datalust/seq:latest

  sqldata:
    image: postgres

  bot-api:
    image: ${REGISTRY:-eblackcountry}/bot.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Bot/Bot.API/Dockerfile
    depends_on:
      - sqldata

  bot-backgroundtasks:
    image: ${REGISTRY:-eblackcountry}/bot.backgroundtasks:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Bot/Bot.BackgroundTasks/Dockerfile
    depends_on:
      - sqldata

  webstatus:
    image: ${REGISTRY:-eblackcountry}/webstatus:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Web/WebStatus/Dockerfile

  webspa:
    image: ${REGISTRY:-eblackcountry}/webspa:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Web/WebSPA/Dockerfile