version: "3.4"

services:
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  sqldata:
    environment:
      - POSTGRES_PASSWORD=Pass@word
    volumes:
      - eblackcountry-sqldata:/var/lib/postgresql/data

  bot-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${EBLACKCOUNTRY_BOT_DB:-Server=sqldata;Database=eBlackCountry.Services.BotDb;User Id=postgres;Password=Pass@word}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
      - Serilog__MinimumLevel__Override__Bot.API=Verbose
    ports:
      - "5102:80"

  bot-backgroundtasks:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${EBLACKCOUNTRY_BOT_DB:-Server=sqldata;Database=eBlackCountry.Services.BotDb;User Id=sa;Password=Pass@word}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
      - Serilog__MinimumLevel__Override__Bot.API=Verbose
    ports:
      - "5111:80"

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__1__Name=WebSPA HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://webspa/hc
      - HealthChecksUI__HealthChecks__4__Name=Bot HTTP Check
      - HealthChecksUI__HealthChecks__4__Uri=http://bot-api/hc
      - HealthChecksUI__HealthChecks__12__Name=Bot HTTP Background Check
      - HealthChecksUI__HealthChecks__12__Uri=http://bot-backgroundtasks/hc
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5107:80"

  webspa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - BotUrl=http://${EBLACKCOUNTRY_EXTERNAL_DNS_NAME_OR_IP}:5102
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5104:80"

volumes:
  eblackcountry-sqldata:
    external: false